const properties = [
  // ─── LONAVALA & PAWNA (29) ───
  {
    id: 1,
    name: "Avion Hotel",
    type: "Budget",
    location: "Lonavala",
    price: 4500,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900&q=80"],
    description: "Centrally located hotel offering comfortable access to Lonavala's primary markets and viewpoints. Ideal for quick weekend breaks without breaking the bank.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Parking", "Room Service"],
    highlight: "Budget Gem", available: true, deal: false
  },
  {
    id: 2,
    name: "Novotel Lonavala",
    type: "Resort",
    location: "Lonavala",
    price: 13500,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=80"],
    description: "Premium contemporary resort featuring expansive swimming spaces, highly rated multi-cuisine restaurants, and beautiful hill views.",
    amenities: ["Infinity Pool", "Free WiFi", "Air Conditioning", "Restaurant", "Spa", "Bar"],
    highlight: "Premium Resort", available: true, deal: true
  },
  {
    id: 3,
    name: "Fariyas Resort",
    type: "Resort",
    location: "Lonavala",
    price: 14000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&q=80"],
    description: "A legendary luxury resort nestled in Frichley Hills, famously known for its indoor water park, premium spa retreats, and deluxe valley suites.",
    amenities: ["Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "Bar", "Room Service"],
    highlight: "Water Park Resort", available: true, deal: false
  },
  {
    id: 4,
    name: "Arova Woods",
    type: "Boutique",
    location: "Lonavala",
    price: 6800,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=900&q=80"],
    description: "Charming stay wrapped within dense green foliage, balancing minimalist wood decor with peaceful natural surroundings.",
    amenities: ["Free WiFi", "Air Conditioning", "Nature Trails", "Parking"],
    highlight: "Nature Retreat", available: true, deal: false
  },
  {
    id: 5,
    name: "Picaddle Boutique Resort",
    type: "Boutique",
    location: "Lonavala",
    price: 8500,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80"],
    description: "Luxury boutique experience sitting comfortably in the heart of town, highlighting customized service architecture and excellent urban styling.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Spa", "Fine Dining"],
    highlight: "Boutique Comfort", available: true, deal: true
  },
  {
    id: 6,
    name: "Trikaya Retreat",
    type: "Resort",
    location: "Lonavala",
    price: 9000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1470246973918-29a93221c455?w=900&q=80"],
    description: "Eco-wilderness retreat positioned high on a hilltop ridges. Experience wilderness hikes, misty mornings, and farm-fresh organic meals.",
    amenities: ["Nature Trails", "Bonfire", "Free WiFi", "Home Cooking", "Parking"],
    highlight: "Eco Luxury", available: true, deal: false
  },
  {
    id: 7,
    name: "Enrise by Sayaji",
    type: "Boutique",
    location: "Lonavala",
    price: 7500,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?w=900&q=80"],
    description: "An elegant enterprise property focusing on modern travel layouts, excellent business infrastructure, and upscale dining lounges.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "24hr Room Service"],
    highlight: "Business Class", available: true, deal: false
  },
  {
    id: 8,
    name: "Arboreal Resort, Pawna",
    type: "Resort",
    location: "Pawna",
    price: 11500,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=900&q=80"],
    description: "Tree-canopy structural stays looking out directly over the brilliant waters of Lake Pawna. Total serenity out in nature.",
    amenities: ["Lake View", "Nature Trails", "Free WiFi", "Air Conditioning", "Private Deck"],
    highlight: "Lake View", available: true, deal: true
  },
  {
    id: 9,
    name: "The White Resort & Spa, Pawna",
    type: "Resort",
    location: "Pawna",
    price: 15500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80"],
    description: "Santorini-themed white infrastructure design elements right against Pawna lake edges. Massive wellness setups and deep massage facilities.",
    amenities: ["Lake View", "Spa", "Infinity Pool", "Free WiFi", "Air Conditioning", "Fine Dining"],
    highlight: "Lakefront Luxury", available: true, deal: false
  },
  {
    id: 10,
    name: "Varu Woods, Lonavala",
    type: "Villa",
    location: "Lonavala",
    price: 19500,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80"],
    description: "Ultra-premium private wood villa featuring minimalist modern styling, its own plunge pool, and lush green lawns.",
    amenities: ["Private Pool", "Free WiFi", "Full Kitchen", "Caretaker", "BBQ", "Air Conditioning"],
    highlight: "Private Plunge Pool", available: true, deal: false
  },
  {
    id: 11,
    name: "Rhythm Lonavala – All Suite Resort",
    type: "Resort",
    location: "Lonavala",
    price: 16500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80"],
    description: "Premium all-suite premium estate designed around traditional courtyard architectures. Immense open fields and luxury family villas.",
    amenities: ["Outdoor Pool", "Spa", "Free WiFi", "Air Conditioning", "Bar", "Fine Dining"],
    highlight: "All-Suite Premium", available: true, deal: true
  },
  {
    id: 12,
    name: "The Fern Ecotel Hotel, Lonavala",
    type: "Resort",
    location: "Lonavala",
    price: 10500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80"],
    description: "Environmentally certified luxury property integrating green architecture, pristine valley vistas, and award-winning dining setups.",
    amenities: ["Outdoor Pool", "Free WiFi", "Air Conditioning", "Eco Friendly", "Restaurant"],
    highlight: "Eco Friendly", available: true, deal: false
  },
  {
    id: 13,
    name: "Regenta SGS Hotel",
    type: "Resort",
    location: "Lonavala",
    price: 8000,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&q=80"],
    description: "Comfortable, modern city-edge property offering comprehensive event halls, premium room bedding setups, and accessible transit routes.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Outdoor Pool", "Room Service"],
    highlight: "Reliable Stay", available: true, deal: false
  },
  {
    id: 14,
    name: "Ikshana Resort & Spa",
    type: "Resort",
    location: "Lonavala",
    price: 12000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80"],
    description: "High-altitude resort setup showcasing extensive mountain viewpoints, state-of-the-art steam facilities, and fine terrace bars.",
    amenities: ["Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "Mountain View"],
    highlight: "Mountain View", available: true, deal: true
  },
  {
    id: 15,
    name: "Azure Lakeside Resort",
    type: "Resort",
    location: "Pawna",
    price: 11000,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&q=80"],
    description: "Waterfront resort compound perfectly optimized for peaceful sunset views over Pawna lake. Features specialized boat mooring strips.",
    amenities: ["Lake View", "Free WiFi", "Outdoor Pool", "Restaurant", "Kayaking"],
    highlight: "Lake View", available: true, deal: false
  },
  {
    id: 16,
    name: "The Chhavani",
    type: "Heritage",
    location: "Lonavala",
    price: 14500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1533105079780-92b9be482077?w=900&q=80"],
    description: "Luxury camping and canvas suites mimicking royal historical army bases. Exceptional heritage interior items mixed with modern fixtures.",
    amenities: ["Bonfire", "Free WiFi", "Air Conditioning", "Heritage Walk", "Private Deck"],
    highlight: "Heritage Canvas", available: true, deal: false
  },
  {
    id: 17,
    name: "Meritas Countryside Resort",
    type: "Resort",
    location: "Lonavala",
    price: 6500,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=900&q=80"],
    description: "Family-oriented green layout resort focusing on multi-tier garden systems, kids gaming zones, and relaxing lounge arenas.",
    amenities: ["Free WiFi", "Outdoor Pool", "Air Conditioning", "Parking", "Room Service"],
    highlight: "Family Choice", available: true, deal: true
  },
  {
    id: 18,
    name: "Meritas Aura Resort",
    type: "Resort",
    location: "Lonavala",
    price: 7000,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?w=900&q=80"],
    description: "A compact modern oasis featuring high-speed digital amenities, sleek pool areas, and direct access to primary highway routes.",
    amenities: ["Free WiFi", "Outdoor Pool", "Air Conditioning", "Restaurant"],
    highlight: "Modern Oasis", available: true, deal: false
  },
  {
    id: 19,
    name: "Meritas Crystal Resort",
    type: "Resort",
    location: "Lonavala",
    price: 7500,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1554080353-a576cf803bda?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1554080353-a576cf803bda?w=900&q=80"],
    description: "Features crystal clear central pool systems, up-market suite layout rooms, and excellent continental menu selections.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Restaurant", "Spa"],
    highlight: "Premium Stay", available: true, deal: false
  },
  {
    id: 20,
    name: "Hotel Gautam",
    type: "Budget",
    location: "Lonavala",
    price: 5500,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1582610116397-edb318620f90?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1582610116397-edb318620f90?w=900&q=80"],
    description: "Highly recognized family destination option famous for pure-vegetarian multi-cuisine operations and pleasant central courtyard decks.",
    amenities: ["Free WiFi", "Outdoor Pool", "Restaurant", "Air Conditioning", "Parking"],
    highlight: "Pure Veg Hub", available: true, deal: false
  },
  {
    id: 21,
    name: "Cloud 9 Hill Resort",
    type: "Resort",
    location: "Lonavala",
    price: 9500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80"],
    description: "Sits far up Amby Valley road paths, frequently surrounded by floating low cloud clusters. Breathtaking high-altitude valley viewpoints.",
    amenities: ["Mountain View", "Outdoor Pool", "Free WiFi", "Bonfire", "Restaurant"],
    highlight: "Cloud Canopy", available: true, deal: true
  },
  {
    id: 22,
    name: "Ethereal Dunes, Pawna",
    type: "Overwater",
    location: "Pawna",
    price: 25000,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=900&q=80"],
    description: "Stunning boutique villas reaching out across Pawna lake lines. Glass floor panels, private boat docking space, and unmatched ultimate luxury.",
    amenities: ["Glass Floor Panel", "Ocean Access Ladder", "Lake View", "Private Pool", "Butler Service"],
    highlight: "Lake Premium", available: true, deal: false
  },
  {
    id: 23,
    name: "Bliss Nirvana Estate",
    type: "Villa",
    location: "Lonavala",
    price: 45000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80"],
    description: "Massive 10 BHK private premium mansion layout designed exclusively for massive family operations. Includes sound stages, full chefs, and massive private lawn yards.",
    amenities: ["Private Pool", "Full Kitchen", "Chef on Request", "Free WiFi", "Sound System", "Caretaker"],
    highlight: "10 BHK Mansion", available: true, deal: false
  },
  {
    id: 24,
    name: "StayVista by Vana",
    type: "Villa",
    location: "Lonavala",
    price: 22000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&q=80"],
    description: "Highly structural luxury glass villa setup ensuring absolute visual transparency across surrounding mountain ridges. Complete isolated calm.",
    amenities: ["Private Pool", "Free WiFi", "Air Conditioning", "Full Kitchen", "Caretaker"],
    highlight: "Glass Architecture", available: true, deal: true
  },
  {
    id: 25,
    name: "Lagoona Resort",
    type: "Resort",
    location: "Lonavala",
    price: 8500,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1546548970-71785318a17b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1546548970-71785318a17b?w=900&q=80"],
    description: "India's first environmentally conscious eco resort integrating a massive artificial lagoon lake structure within its central floor layout.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Lagoon Mooring", "Restaurant"],
    highlight: "Lagoon Core", available: true, deal: false
  },
  {
    id: 26,
    name: "Aamby Valley Resort",
    type: "Resort",
    location: "Lonavala",
    price: 18000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1518733057094-95b53143d2a7?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1518733057094-95b53143d2a7?w=900&q=80"],
    description: "Sprawling independent master-planned premium city township showcasing private runways, massive water complexes, and elite golf spaces.",
    amenities: ["Private Beach", "Infinity Pool", "Free WiFi", "Spa", "Golf", "Bar"],
    highlight: "Independent City", available: true, deal: false
  },
  {
    id: 27,
    name: "D.A.T.A. Adventure Resort",
    type: "Resort",
    location: "Lonavala",
    price: 15000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=900&q=80"],
    description: "Military-grade extreme tactical survival adventure resort layout offering custom obstacle pathways and high-grade safety drill master plans.",
    amenities: ["Nature Trails", "Free WiFi", "Air Conditioning", "Outdoor Pool", "Tactical Training"],
    highlight: "Extreme Adventure", available: true, deal: false
  },
  {
    id: 28,
    name: "Antheia – A Luxury Boutique Resort",
    type: "Boutique",
    location: "Lonavala",
    price: 11000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=900&q=80"],
    description: "Exclusive destination focusing heavily on European classic design elements, private botanical display rooms, and high-tier cocktail lounges.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Fine Dining", "Bar"],
    highlight: "Euro Classic", available: true, deal: true
  },
  {
    id: 29,
    name: "VITS Lonavala",
    type: "Budget",
    location: "Lonavala",
    price: 5000,
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1496568818309-53d7c7753022?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1496568818309-53d7c7753022?w=900&q=80"],
    description: "Highly accessible transit-stop business travel hub hotel perfectly aligned right adjacent to the primary rail junction paths.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Parking", "Room Service"],
    highlight: "Station Proximity", available: true, deal: false
  },

  // ─── KARJAT (12) ───
  {
    id: 30,
    name: "Stone Water by Zuper",
    type: "Resort",
    location: "Karjat",
    price: 12500,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&q=80"],
    description: "Exquisite stone architectures framed by running natural river systems. Offers high-level spa therapy programs.",
    amenities: ["Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "Nature Trails"],
    highlight: "Riverfront Stone", available: true, deal: true
  },
  {
    id: 31,
    name: "The Forest Club Resort",
    type: "Resort",
    location: "Karjat",
    price: 14000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&q=80"],
    description: "Boasts India's largest direct loop step-out executive pool layout structure. Step directly from your villa deck straight into the pool water lanes.",
    amenities: ["Infinity Pool", "Free WiFi", "Air Conditioning", "Bar", "Fine Dining"],
    highlight: "Step-out Pool Access", available: true, deal: false
  },
  {
    id: 32,
    name: "Radisson Blu Plaza Resort",
    type: "Resort",
    location: "Karjat",
    price: 16000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900&q=80"],
    description: "Five-star international resort compound showing magnificent view architectures across Ulhas river pathways.",
    amenities: ["Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "Fine Dining", "Bar"],
    highlight: "5-Star Premium", available: true, deal: false
  },
  {
    id: 33,
    name: "U Rivergate Resort & Spa",
    type: "Resort",
    location: "Karjat",
    price: 11000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=900&q=80"],
    description: "Peaceful riverbank resort focusing heavily on meditation, yoga deck platforms, and customized deep massage treatment zones.",
    amenities: ["Outdoor Pool", "Yoga Deck", "Free WiFi", "Air Conditioning", "Spa"],
    highlight: "Riverfront Calm", available: true, deal: true
  },
  {
    id: 34,
    name: "Mango Tree Farm Resort",
    type: "Budget",
    location: "Karjat",
    price: 5500,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=900&q=80"],
    description: "Rustic agricultural plantation compound offering deep country experiences, local organic dining options, and birdwatching trails.",
    amenities: ["Free WiFi", "Home Cooking", "Nature Trails", "Bonfire", "Parking"],
    highlight: "Agro Farm", available: true, deal: false
  },
  {
    id: 35,
    name: "Ayush Resort",
    type: "Budget",
    location: "Karjat",
    price: 4800,
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1564507592333-c60657eea523?w=900&q=80"],
    description: "Affordable basic base layout centered on absolute simplicity, family weekend rooms, and classic Indian dining structures.",
    amenities: ["Free WiFi", "Outdoor Pool", "Air Conditioning", "Restaurant", "Parking"],
    highlight: "Budget Base", available: true, deal: false
  },
  {
    id: 36,
    name: "Monteria Village",
    type: "Heritage",
    location: "Karjat",
    price: 7500,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1514894780063-cc5012309196?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1514894780063-cc5012309196?w=900&q=80"],
    description: "Immersive traditional country village structural experience highlighting pottery zones, folk dance structures, and old heritage living concepts.",
    amenities: ["Heritage Walk", "Cultural Performances", "Free WiFi", "Restaurant", "Parking"],
    highlight: "Village Heritage", available: true, deal: false
  },
  {
    id: 37,
    name: "Oleander Farms",
    type: "Resort",
    location: "Karjat",
    price: 17000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80"],
    description: "Highly elite luxury country estate compound featuring customized vineyard rows, premium microbreweries, and high-end equestrian horse tracks.",
    amenities: ["Infinity Pool", "Bar", "Free WiFi", "Air Conditioning", "Fine Dining", "Wine Tasting"],
    highlight: "Premium Estate", available: true, deal: true
  },
  {
    id: 38,
    name: "The Nest by Oleander Farms",
    type: "Villa",
    location: "Karjat",
    price: 26000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80"],
    description: "Ultra-high-end secluded private estate sanctuary building inside Oleander lines. Absolute personal butler setups and architectural superiority.",
    amenities: ["Private Pool", "Butler Service", "Free WiFi", "Air Conditioning", "Chef on Request"],
    highlight: "Elite Sanctuary", available: true, deal: false
  },
  {
    id: 39,
    name: "River Estates Luxury Resort & Spa",
    type: "Resort",
    location: "Karjat",
    price: 13000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=900&q=80"],
    description: "Modern, high-line villa clusters positioned cleanly along the fast-flowing mountain rivers. Complete world-class luxury layouts.",
    amenities: ["Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "River View"],
    highlight: "River Luxury", available: true, deal: false
  },
  {
    id: 40,
    name: "Spicy Mango – Saveda Farms",
    type: "Villa",
    location: "Karjat",
    price: 9000,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80"],
    description: "Charming independent farm cottage complex featuring broad wrap-around wood balconies, organic mango field spaces, and deep rustic styling.",
    amenities: ["Free WiFi", "Full Kitchen", "Caretaker", "Bonfire", "Garden Hammocks"],
    highlight: "Farm Cottage", available: true, deal: true
  },
  {
    id: 41,
    name: "The Boat Club Karjat",
    type: "Boutique",
    location: "Karjat",
    price: 10500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?w=900&q=80"],
    description: "Water sports boutique resort setup providing direct water launch platforms, speed boat operations, and river-facing glass suites.",
    amenities: ["River View", "Kayaking", "Free WiFi", "Air Conditioning", "Restaurant"],
    highlight: "Water Sports Hub", available: false, deal: false
  },

  // ─── IGATPURI (18) ───
  {
    id: 42,
    name: "Igatpuri Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 6000,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=900&q=80"],
    description: "Classic foundational hill-station resort option boasting broad green valley views and high-comfort basic bedding layouts.",
    amenities: ["Free WiFi", "Outdoor Pool", "Air Conditioning", "Restaurant", "Parking"],
    highlight: "Valley Base", available: true, deal: false
  },
  {
    id: 43,
    name: "Tropical Retreat by Zuper",
    type: "Resort",
    location: "Igatpuri",
    price: 11500,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=900&q=80"],
    description: "Expansive high-end luxury wellness land footprint. Multi-lane swimming channels, vast sports fields, and high-altitude mist view decks.",
    amenities: ["Infinity Pool", "Free WiFi", "Air Conditioning", "Spa", "Bar", "Fine Dining"],
    highlight: "Premium Wellness", available: true, deal: true
  },
  {
    id: 44,
    name: "Rainforest Resort Igatpuri",
    type: "Resort",
    location: "Igatpuri",
    price: 8000,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=900&q=80"],
    description: "Perched beautifully right along the dramatic drops of Kasara Ghat slopes. Exceptional panoramic cloud-canopy view horizons.",
    amenities: ["Outdoor Pool", "Free WiFi", "Air Conditioning", "Restaurant", "Mountain View"],
    highlight: "Ghat Panoramas", available: true, deal: false
  },
  {
    id: 45,
    name: "Manas Resort with Petting Zoo",
    type: "Resort",
    location: "Igatpuri",
    price: 9500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?w=900&q=80"],
    description: "Highly unique family vacation luxury hub showcasing an active, professionally monitored exotic animal petting zoo and organic nursery lines.",
    amenities: ["Outdoor Pool", "Petting Zoo", "Free WiFi", "Air Conditioning", "Restaurant"],
    highlight: "Petting Zoo Core", available: true, deal: true
  },
  {
    id: 46,
    name: "Shwas Island Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 13000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=900&q=80"],
    description: "Secluded island ecosystem resort built straight inside deep backwater dam lakes. Absolute isolated calm and premium boat transit.",
    amenities: ["Lake View", "Boat Rides", "Free WiFi", "Air Conditioning", "Private Deck"],
    highlight: "Island Sanctuary", available: true, deal: false
  },
  {
    id: 47,
    name: "Wabi Sabi Resort",
    type: "Boutique",
    location: "Igatpuri",
    price: 10500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1545749411-060163731687?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1545749411-060163731687?w=900&q=80"],
    description: "Japanese structural architectural design philosophy integrating raw organic textures, calm rock pools, and zen meditation grounds.",
    amenities: ["Free WiFi", "Air Conditioning", "Yoga Deck", "Spa", "Fine Dining"],
    highlight: "Zen Architecture", available: true, deal: false
  },
  {
    id: 48,
    name: "Rakabi – The Fern, Igatpuri",
    type: "Resort",
    location: "Igatpuri",
    price: 9000,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80"],
    description: "Up-market eco-sensitive business and leisure hotel. Top-grade energy-saving architecture with highly refined interior comforts.",
    amenities: ["Free WiFi", "Air Conditioning", "Eco Friendly", "Outdoor Pool", "Restaurant"],
    highlight: "Eco Premium", available: true, deal: true
  },
  {
    id: 49,
    name: "The Mountain Shadow Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 12000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80"],
    description: "Sits silently right underneath historical high mountain fort peak shadows. Incredible multi-directional trekking pathways.",
    amenities: ["Mountain View", "Nature Trails", "Infinity Pool", "Free WiFi", "Bar"],
    highlight: "Peak Shadow Vistas", available: true, deal: false
  },
  {
    id: 50,
    name: "Touchwood Bliss, Igatpuri",
    type: "Budget",
    location: "Igatpuri",
    price: 5000,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1470246973918-29a93221c455?w=900&q=80"],
    description: "Eco glamping and wood cabin framework targeting absolute minimal tech stress, heavy organic eating options, and bonfire fields.",
    amenities: ["Bonfire", "Home Cooking", "Free WiFi", "Nature Trails", "Parking"],
    highlight: "Glamping Oasis", available: true, deal: false
  },
  {
    id: 51,
    name: "Ark Lake Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 10000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=900&q=80"],
    description: "Modern structural layout framing pristine high lake basins. Comprehensive watercraft sport items available daily.",
    amenities: ["Lake View", "Kayaking", "Free WiFi", "Outdoor Pool", "Restaurant"],
    highlight: "Lake View", available: true, deal: true
  },
  {
    id: 52,
    name: "Manas Lifestyle Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 8500,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1546412414-8035e1776c9a?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1546412414-8035e1776c9a?w=900&q=80"],
    description: "Expansive green garden layouts containing massive premium spa therapy structures and excellent multi-cuisine operations.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Spa", "Fine Dining"],
    highlight: "Lifestyle Premium", available: true, deal: false
  },
  {
    id: 53,
    name: "Regenta Place, Igatpuri",
    type: "Resort",
    location: "Igatpuri",
    price: 7800,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&q=80"],
    description: "Highly structural luxury building containing state of the art conference design options and wide balcony views.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Outdoor Pool", "Room Service"],
    highlight: "Corporate Deluxe", available: true, deal: false
  },
  {
    id: 54,
    name: "Astoria Lake Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 11000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=900&q=80"],
    description: "Beautifully aligned stone cottages looking directly into vast water bodies. Complete private deck design features.",
    amenities: ["Lake View", "Free WiFi", "Air Conditioning", "Private Deck", "Restaurant"],
    highlight: "Lakefront Stone", available: true, deal: true
  },
  {
    id: 55,
    name: "Dewdrops Boutique Retreat",
    type: "Boutique",
    location: "Igatpuri",
    price: 6800,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80"],
    description: "Cozy modern villa rooms surrounding clean inner central courtyard systems. Extremely quiet urban escape footprint.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Parking", "Room Service"],
    highlight: "Boutique Retreat", available: true, deal: false
  },
  {
    id: 56,
    name: "The Blue Lake Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 10500,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=900&q=80"],
    description: "Integrates deeply with adjacent historical deep blue lake networks. Offers elite open air lakeside dining.",
    amenities: ["Lake View", "Free WiFi", "Outdoor Pool", "Restaurant", "Bonfire"],
    highlight: "Blue Waters", available: true, deal: false
  },
  {
    id: 57,
    name: "Relax Adventure Resort",
    type: "Budget",
    location: "Igatpuri",
    price: 4900,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1533240332313-0db49b459ad6?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1533240332313-0db49b459ad6?w=900&q=80"],
    description: "Optimized specifically for high-intensity tracking, night safaris, and outdoor open air adventure obstacles.",
    amenities: ["Nature Trails", "Free WiFi", "Bonfire", "Parking", "Attached Bathroom"],
    highlight: "Adventure Hub", available: true, deal: false
  },
  {
    id: 58,
    name: "Savannah Lake Resort",
    type: "Resort",
    location: "Igatpuri",
    price: 12500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?w=900&q=80"],
    description: "Luxury safari-tent theme architectures providing endless uninhibited horizon views over massive lake environments.",
    amenities: ["Lake View", "Infinity Pool", "Free WiFi", "Air Conditioning", "Fine Dining"],
    highlight: "Safari Theme Luxury", available: true, deal: true
  },
  {
    id: 59,
    name: "Mastiff Select Rivera Resort",
    type: "Resort",
    location: "Nashik",
    price: 8500,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=900&q=80"],
    description: "Premium property sitting elegantly on the serene borders of Nashik and Igatpuri, looking out over rolling river banks.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Restaurant", "Harbour View"],
    highlight: "Rivera Luxury", available: true, deal: false
  },

  // ─── BHANDARDARA (7) ───
  {
    id: 60,
    name: "The Ashok Sarovar",
    type: "Resort",
    location: "Bhandardara",
    price: 9500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=900&q=80"],
    description: "Premium grand heritage architectural resort framing unparalleled views of the clean Arthur Lake basins.",
    amenities: ["Lake View", "Free WiFi", "Air Conditioning", "Outdoor Pool", "Fine Dining"],
    highlight: "Sarovar Luxury", available: true, deal: true
  },
  {
    id: 61,
    name: "Anandvan Resort",
    type: "Resort",
    location: "Bhandardara",
    price: 14000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=900&q=80"],
    description: "High-end eco luxury treehouses and mountain villas set beautifully at the highest hill points of Bhandardara.",
    amenities: ["Mountain View", "Private Deck", "Free WiFi", "Spa", "Nature Trails"],
    highlight: "Eco Treehouses", available: true, deal: false
  },
  {
    id: 62,
    name: "The Yash Resort",
    type: "Resort",
    location: "Bhandardara",
    price: 7500,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=900&q=80"],
    description: "Excellent layout structures optimized heavily for direct valley exploration paths, complete family comfort focus.",
    amenities: ["Free WiFi", "Outdoor Pool", "Air Conditioning", "Restaurant", "Parking"],
    highlight: "Family Vacation", available: true, deal: false
  },
  {
    id: 63,
    name: "The Paradise Retreat",
    type: "Boutique",
    location: "Bhandardara",
    price: 8500,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=900&q=80"],
    description: "Boutique villa clusters showing dramatic, sweeping views of clean mountain waterfall systems.",
    amenities: ["Free WiFi", "Air Conditioning", "Nature Trails", "Restaurant", "Bonfire"],
    highlight: "Waterfall Retreat", available: true, deal: true
  },
  {
    id: 64,
    name: "Riverside Resort Bhandardara",
    type: "Budget",
    location: "Bhandardara",
    price: 4800,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80"],
    description: "Quiet, rustic structural cabins facing the flowing Pravara river streams directly. Unmatched pricing value.",
    amenities: ["River View", "Free WiFi", "Home Cooking", "Parking", "Hot Water"],
    highlight: "River Bank Value", available: true, deal: false
  },
  {
    id: 65,
    name: "Blue Water Resort",
    type: "Resort",
    location: "Bhandardara",
    price: 9000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=900&q=80"],
    description: "Positioned directly on wide blue dam reservoir borders. Stellar setups for night fire gazing and outdoor barbecue nights.",
    amenities: ["Lake View", "Outdoor Pool", "Free WiFi", "Air Conditioning", "BBQ"],
    highlight: "Lakeside Glamp", available: true, deal: false
  },
  {
    id: 66,
    name: "Taalish Boutique Resort",
    type: "Boutique",
    location: "Bhandardara",
    price: 11000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80"],
    description: "Premium architectural sanctuary providing elite privacy, specialized organic dining, and direct boat access.",
    amenities: ["Lake View", "Free WiFi", "Air Conditioning", "Fine Dining", "Boat Rides"],
    highlight: "Luxury Boutique", available: true, deal: true
  },

  // ─── NASHIK (22) ───
  {
    id: 67,
    name: "Grape County Eco Resort & Spa",
    type: "Resort",
    location: "Nashik",
    price: 13000,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80"],
    description: "Enormous eco-wilderness land compound featuring high-grade lake villas, active equestrian trails, kayaking, and broad forest tracks.",
    amenities: ["Nature Trails", "Infinity Pool", "Free WiFi", "Eco Friendly", "Kayaking", "Spa"],
    highlight: "Eco Wilderness", available: true, deal: true
  },
  {
    id: 68,
    name: "Viveda Wellness Retreat",
    type: "Resort",
    location: "Nashik",
    price: 16000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1545749411-060163731687?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1545749411-060163731687?w=900&q=80"],
    description: "Highly structural luxury ayurvedic wellness space focusing strictly on health rejuvenation, pure organic diets, and silent rock pools.",
    amenities: ["Spa", "Yoga Deck", "Free WiFi", "Air Conditioning", "Home Cooking"],
    highlight: "Ayurveda Luxury", available: true, deal: false
  },
  {
    id: 69,
    name: "Little Cove Nature Resort",
    type: "Boutique",
    location: "Nashik",
    price: 9000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=900&q=80"],
    description: "Delightful boutique wood logs arranged along secluded dam basins. Complete slow-living mental decompression setup.",
    amenities: ["Lake View", "Free WiFi", "Nature Trails", "Bonfire", "Outdoor Seating"],
    highlight: "Log Cabin Calm", available: true, deal: false
  },
  {
    id: 71,
    name: "Suma Adventure & Resort",
    type: "Resort",
    location: "Nashik",
    price: 8000,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1533240332313-0db49b459ad6?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1533240332313-0db49b459ad6?w=900&q=80"],
    description: "High-intensity property packing broad zip-line setups, massive tracking tracks, and high wall scaling infrastructures.",
    amenities: ["Free WiFi", "Outdoor Pool", "Air Conditioning", "Tactical Training", "Restaurant"],
    highlight: "Adventure Hub", available: true, deal: true
  },
  {
    id: 72,
    name: "The Haven by Sula",
    type: "Villa",
    location: "Nashik",
    price: 28000,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&q=80"],
    description: "Sula's most elite ultra-exclusive private luxury estate villa layout. Breathtaking floor design overlooking historic private vine fields.",
    amenities: ["Private Pool", "Butler Service", "Free WiFi", "Air Conditioning", "Wine Tasting", "Full Kitchen"],
    highlight: "Sula Elite", available: true, deal: false
  },
  {
    id: 73,
    name: "Savana Lake Resort Nashik",
    type: "Resort",
    location: "Nashik",
    price: 11000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80"],
    description: "Magnificent agro-tourism luxury setup flanked closely by tranquil lake waters and organic farming hills.",
    amenities: ["Lake View", "Free WiFi", "Outdoor Pool", "Farming", "Nature Trails"],
    highlight: "Agro Luxury", available: true, deal: false
  },
  {
    id: 74,
    name: "Caves Country Resort",
    type: "Budget",
    location: "Nashik",
    price: 5000,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?w=900&q=80"],
    description: "Positioned directly close to historic rock caves layouts. High value budget structural units for clean tourism transit.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Parking", "Room Service"],
    highlight: "Cave Proximity", available: true, deal: true
  },
  {
    id: 75,
    name: "The Source at Sula",
    type: "Resort",
    location: "Nashik",
    price: 15000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=900&q=80"],
    description: "India's landmark flagship vineyard resort destination property. Tuscan structural theme styling, fine cellars, elite wine tasting.",
    amenities: ["Infinity Pool", "Wine Tasting", "Spa", "Free WiFi", "Air Conditioning", "Bar"],
    highlight: "Flagship Vineyard", available: true, deal: false
  },
  {
    id: 76,
    name: "Express Inn",
    type: "Resort",
    location: "Nashik",
    price: 9500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=900&q=80"],
    description: "High-rise luxury urban business hotel presenting stellar city skyline vistas, fine dining zones, and massive lounge bars.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Spa", "Fine Dining", "Bar"],
    highlight: "Urban Luxury", available: true, deal: true
  },
  {
    id: 77,
    name: "Gateway Nashik by Taj",
    type: "Resort",
    location: "Nashik",
    price: 17500,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80"],
    description: "Ultra-premium Taj hospitality campus stretching across beautifully sculpted gardens right at Ambad hill edges.",
    amenities: ["Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "Fine Dining", "Butler Service"],
    highlight: "Taj Premium", available: true, deal: false
  },
  {
    id: 78,
    name: "Beyond by Sula",
    type: "Resort",
    location: "Nashik",
    price: 16500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=900&q=80"],
    description: "Minimalist high-line sanctuary layout built right along Gangapur Dam edges. Total privacy mixed with elite wine amenities.",
    amenities: ["Lake View", "Infinity Pool", "Wine Tasting", "Free WiFi", "Air Conditioning"],
    highlight: "Lakeside Vines", available: true, deal: true
  },
  {
    id: 79,
    name: "Aria Resort & Spa",
    type: "Resort",
    location: "Nashik",
    price: 12000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&q=80"],
    description: "Stellar lakefront property framing architectural infinity pool loops that blend cleanly into Gangapur backwaters.",
    amenities: ["Lake View", "Infinity Pool", "Spa", "Free WiFi", "Air Conditioning", "Bar"],
    highlight: "Infinity Waterfront", available: true, deal: false
  },
  {
    id: 80,
    name: "Courtyard by Marriott Nashik",
    type: "Resort",
    location: "Nashik",
    price: 11500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=80"],
    description: "World class premium corporate and leisure high rise framework demonstrating pristine hospitality metrics and top-tier gyms.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Fine Dining", "Bar"],
    highlight: "Marriott Standard", available: true, deal: false
  },
  {
    id: 81,
    name: "Regenta Resort Soma Vine Village",
    type: "Resort",
    location: "Nashik",
    price: 13500,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80"],
    description: "Premium lake facing boutique vineyard houses containing active adventure parks and elite grape crushing complexes.",
    amenities: ["Lake View", "Wine Tasting", "Outdoor Pool", "Free WiFi", "Air Conditioning"],
    highlight: "Vineyard Village", available: true, deal: true
  },
  {
    id: 82,
    name: "Radisson Blu Hotel & Spa Nashik",
    type: "Resort",
    location: "Nashik",
    price: 15500,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80"],
    description: "Nestled right at the base of historical Pandavleni Caves hills. Unmatched premium resort lawns and extensive international luxury treatment lounges.",
    amenities: ["Infinity Pool", "Spa", "Mountain View", "Free WiFi", "Air Conditioning", "Bar"],
    highlight: "Elite Luxury Footprint", available: true, deal: false
  },
  {
    id: 83,
    name: "Holiday Inn Express Nashik",
    type: "Budget",
    location: "Nashik",
    price: 4500,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1496568818309-53d7c7753022?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1496568818309-53d7c7753022?w=900&q=80"],
    description: "Sleek, highly efficient smart transit hub hotel offering clean compact layouts, fast connectivity setups, and complimentary hot breakfast pipelines.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Parking", "Safe"],
    highlight: "Smart Transit", available: true, deal: false
  },
  {
    id: 84,
    name: "The Vern at BLVD",
    type: "Boutique",
    location: "Nashik",
    price: 7500,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=900&q=80"],
    description: "High aesthetic interior design boutique concept lodging delivering custom boutique environments and top tier urban lounge scenes.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Bar", "Room Service"],
    highlight: "Design Concept", available: true, deal: true
  },
  {
    id: 85,
    name: "Four Points by Sheraton Nashik",
    type: "Resort",
    location: "Nashik",
    price: 10500,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80"],
    description: "Delivers the global gold standard structural security, elegant executive board bedding architectures, and fine dining halls.",
    amenities: ["Free WiFi", "Air Conditioning", "Outdoor Pool", "Fine Dining", "Parking"],
    highlight: "Global Standard", available: true, deal: false
  },
  {
    id: 86,
    name: "Enrise by Sayaji Nashik",
    type: "Boutique",
    location: "Nashik",
    price: 6800,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=900&q=80"],
    description: "Modern, clean enterprise business infrastructure property structured beautifully for quick city transit execution layouts.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Parking", "24hr Concierge"],
    highlight: "Business Smooth", available: true, deal: false
  },
  {
    id: 87,
    name: "VITS Hotel Nashik",
    type: "Budget",
    location: "Nashik",
    price: 5200,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?w=900&q=80"],
    description: "Comfortable value framework hotel providing highly spacious multi-bed layout designs optimized for long corporate operations.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Parking", "Room Service"],
    highlight: "Corporate Value", available: true, deal: false
  },
  {
    id: 88,
    name: "The SSK Solitaire Boutique Hotel",
    type: "Boutique",
    location: "Nashik",
    price: 8000,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80"],
    description: "Intimate and exceptionally polished boutique destination presenting fine custom light engineering systems and wonderful terrace spaces.",
    amenities: ["Free WiFi", "Air Conditioning", "Restaurant", "Spa", "Room Service"],
    highlight: "Polished Boutique", available: true, deal: true
  },
  {
    id: 89,
    name: "River & Sky Resort",
    type: "Resort",
    location: "Nashik",
    price: 11000,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=700&q=80",
    images: ["https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=900&q=80"],
    description: "Exquisite high ridge location where flowing rivers intersect clear sky views. Perfect outdoor open air deck layouts.",
    amenities: ["Harbour View", "Free WiFi", "Air Conditioning", "Outdoor Pool", "Restaurant"],
    highlight: "River Vistas", available: true, deal: false
  }
];